### ISSUE TITLE
Trying To Change The Button/Menu Names

### ISSUE THREAD

**Issue by iGetUploaded** [TejasLamba2006/discord.js-v14-tickets-bot#1]
Hello so I'm just trying to change the names of the button/menu... So Instead of  ( giveaway, special, general ) I'm trying ( general, Questions, report ) but when I go to change them I get interaction failed. Only general stays working I'm not sure what is happening.. 

Also yes I changed the names in the config & setup to the ones I want

**Comment by TejasLamba2006** [comment]
Hey @iGetUploaded, I understand your intentions.

Please note that the provided code comes with no warranty. If you intend to modify or edit it, you should have a good understanding of JavaScript.

Thank you!

**Comment by iGetUploaded** [comment]
Alrighty thanks
